apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: ovirtvms.ovirt.kubevirt.io
spec:
  group: ovirt.kubevirt.io
  names:
    kind: OvirtVm
    listKind: OvirtVmList
    plural: ovirtvms
    singular: ovirtvm
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
