apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: ovirt-vm-operator
rules:
- apiGroups:
  - "upload.cdi.kubevirt.io"
  resources:
  - uploadtokenrequests
  verbs:
  - '*'
- apiGroups:
  - "kubevirt.io"
  resources:
  - "*"
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - ovirt-vm-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - ovirt.kubevirt.io
  resources:
  - '*'
  verbs:
  - '*'
